import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "../components/Sidebar";
import { Toaster } from "@/components/ui/sonner";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} bg-slate-950 h-screen overflow-hidden`}
      >
        <main className="px-8 py-4 w-screen h-full flex flex-col gap-4 overflow-hidden">
          <Header />
          <div className="flex flex-grow flex-1 w-full overflow-hidden">
            <div className="w-full flex-grow">{children}</div>
            <Sidebar />
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
